"""
RAMP Data Validation Report Generator
SIH26080 | JSON + Markdown Report Output

Every ingestion call must produce a ValidationReport, JSON, and Markdown.
No silent failures — always report provenance and quality status.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from ramp.ingestion.base import ValidationReport

logger = logging.getLogger("ramp.validation.report")


def save_validation_report(
    report: ValidationReport,
    output_dir: Path,
    filename_stem: Optional[str] = None,
) -> tuple[Path, Path]:
    """
    Save a ValidationReport to both JSON and Markdown formats.

    Args:
        report:      The validation report to save.
        output_dir:  Target directory (created if absent).
        filename_stem: Base name without extension (auto-generated if None).

    Returns:
        Tuple of (json_path, md_path).
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    if filename_stem is None:
        ts = report.generated_at.strftime("%Y%m%dT%H%M%S")
        safe_name = report.dataset_name.replace(" ", "_").replace("/", "_")
        filename_stem = f"validation_{safe_name}_{ts}"

    json_path = output_dir / f"{filename_stem}.json"
    md_path = output_dir / f"{filename_stem}.md"

    # Save JSON
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(report.to_dict(), f, indent=2, ensure_ascii=False)
    logger.info("Saved validation report: %s", json_path)

    # Save Markdown
    md_content = _render_markdown(report)
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_content)
    logger.info("Saved validation report: %s", md_path)

    return json_path, md_path


def _render_markdown(report: ValidationReport) -> str:
    """Render a ValidationReport as human-readable Markdown."""
    status_icon = "✅" if report.passed else "❌"
    data_mode_note = (
        "\n> ⚠️ **SYNTHETIC_DEMO mode**: These statistics are from generated "
        "data, NOT real observations.\n"
        if report.data_mode.value == "SYNTHETIC_DEMO"
        else ""
    )

    lines = [
        f"# Validation Report: {report.dataset_name}",
        "",
        f"**Status:** {status_icon} {'PASSED' if report.passed else 'FAILED'}",
        f"**Generated:** {report.generated_at.isoformat()}",
        f"**Provider:** `{report.provider_id}`",
        f"**Model:** `{report.model_name}`" if report.model_name else "",
        f"**Data Mode:** `{report.data_mode.value}`",
        data_mode_note,
        "---",
        "",
        "## Temporal Coverage",
        "",
        f"| Field       | Value |",
        f"|-------------|-------|",
        f"| Start       | `{report.time_start or 'N/A'}` |",
        f"| End         | `{report.time_end or 'N/A'}` |",
        f"| Timesteps   | {report.n_timesteps} |",
        "",
        "## Spatial Coverage",
        "",
        f"| Field              | Value |",
        f"|--------------------|-------|",
        f"| Grid Resolution    | {report.grid_resolution_deg or 'N/A'}° |",
        f"| Latitude Points    | {report.n_lat} |",
        f"| Longitude Points   | {report.n_lon} |",
        f"| Total Grid Points  | {report.n_grid_points} |",
        "",
        "## Variables",
        "",
    ]

    if report.variables:
        lines.append("| Variable | Unit |")
        lines.append("|----------|------|")
        for var in report.variables:
            unit = report.units.get(var, "—")
            lines.append(f"| `{var}` | {unit} |")
    else:
        lines.append("*No variables reported.*")

    lines += [
        "",
        "## Data Quality",
        "",
        f"| Metric                | Value |",
        f"|-----------------------|-------|",
        f"| Missing Fraction      | {report.missing_fraction:.4f} ({100*report.missing_fraction:.2f}%) |",
        f"| Invalid Count         | {report.invalid_count} |",
        f"| Suspicious Count      | {report.suspicious_count} |",
        f"| Extreme Value Count   | {report.extreme_value_count} |",
        f"| Duplicate Timestamps  | {report.duplicate_timestamp_count} |",
    ]

    if report.errors:
        lines += ["", "## Errors", ""]
        for e in report.errors:
            lines.append(f"- ❌ {e}")

    if report.warnings:
        lines += ["", "## Warnings", ""]
        for w in report.warnings:
            lines.append(f"- ⚠️ {w}")

    if report.notes:
        lines += ["", "## Notes", "", report.notes]

    lines += [
        "",
        "---",
        "",
        "*Report auto-generated by RAMP validation engine (SIH26080).*",
    ]

    return "\n".join(line for line in lines if line is not None)
